# Lila Shearer, Financial Calculator - Python

# print statement that welcomes user and tells what program does
print("Welcome to Financial Calculator!\n This program is designed to calculate what percentages of your income your expenses, savings, and spending take up.")
# user input - what is your monthly income (variable an input)
income = float (input("What is your monthly income: "))
# user input - what is your monthly rent or mortgage (variable an input)
rent_mortgage = float (input("What is your monthly expense for rent or mortgage: "))
# user input - what is your monthly utilities bill (variable an input)
utilities = float (input("What is your monthly expense for utility: "))
# user input - what is your monthly expense on groceries (variable an input)
groceries = float (input("What is your monthly expense for groceries: "))
# user input - what is your monthly expense for transportation (variable an input)
transportation = float(input("What is your monthly expense for transportation: "))
# calculate savings as 10% of income (income * 0.1) (variable not input)
print(" ")
print("Now to calculate your results!")
savings = (income/10)
savings_percentage = (savings/income * 100)
# calculate spending as income-savings-rent-utilities-groceries-transportation (variable not input)
spending = (income-rent_mortgage-utilities-groceries-transportation)
# calculate percent income of rent/mortgage (rent/income * 100) (variable)
rent_mortgage_percentage = (rent_mortgage/income * 100)
# calculate percent income of utilites (utilities/income * 100) (variable)
utilities_percentage = (utilities/income * 100)
# calculate percent income of groceries (groceries/income * 100) (variable)
groceries_percentage = (groceries/income * 100)
# calculate percent income of transportation (transportation/income * 100) (variable)
transportation_percentage = (transportation/income * 100)
# calculate percent income is spending (speneding/income * 100) (variable)
spending_percentage = (spending/income * 100)
# Your rent expenses are $xx.xx, which is xx% of your income. (print)
print(" ")
print("Here they are:")
print("The amount of money you spend on your rent or mortages is $",rent_mortgage, "which is", rent_mortgage_percentage,"% of your monthly income." )
# Your utilties expenses are $xx.xx, which is xx% of your income. (print)
print("The amount of money you spend on utilties is $",utilities, "which is", utilities_percentage, "% of your monthly income.")
# Your groceries expenses are $xx.xx, which is xx% of your income. (print)
print("The amount of money you spend on groceries is $",groceries, "which is", groceries_percentage, "% of your monthyly income.")
# Your transportion expenses are $xx.xx, which is xx% of your income. (print)
print("The amount of money you spend on transportation is $",transportation, "which is", transportation_percentage, "% of your monthly income.")
# You savings is $xx.xx which is xx% of your income. (print)
print("The amount of money you save is", savings, "which is $",savings_percentage, "% of your monthly income.")
# Your spending is $xx.xx, which is xx% of your income. (print)
print("The amount of money you have left to spend is $",spending, "which is", spending_percentage, "% of your monthly income.")

# almost done, just change how many decimal places there are using round, found in python notes.